---
title: "NIH Progress Report"
author: "Yasmine .G"
date: "Febuary 11, 2020"
output:
  html_document:
  highlight: tango
theme: spacelab
toc: yes
toc_float: yes
---
  
```{r setup, include=FALSE, warning = FALSE}
library(knitr, warn.conflicts = F, quietly = T)
library(tidyr, warn.conflicts = F, quietly = T)
library(dplyr, warn.conflicts = F, quietly = T)
library(ggplot2, warn.conflicts = F, quietly = T)
library(keyringr, warn.conflicts = F, quietly = T)
library(redcapAPI, warn.conflicts = F, quietly = T)
library(REDCapR, warn.conflicts = F, quietly = T)
library(lubridate, warn.conflicts = F, quietly = T)
library(gt, warn.conflicts = F, quietly = T)
#Create path to and api link to RedCaps
credential_label <- "beach_api"
credential_path <- paste(Sys.getenv("USERPROFILE"), '\\DPAPI\\passwords\\', Sys.info()["nodename"], '\\', credential_label, '.txt', sep="")
uri <- "https://redcap.ctsi.ufl.edu/redcap/api/"
beach_token<-decrypt_dpapi_pw(credential_path)
```

```{r variable selection, include=FALSE}
# Create connections
rcon <- redcapConnection(url=uri, token=beach_token)
# variables
desired_fields=c("test_id","mom3t_hispanic",
                 "mom3t_race",
                 "mom3t_baby_sex",
                 "mom3t_baby_hispanic",
                 "mom3t_baby_race")
# participants
participants.records.v1=c("BLS001A",
                     "BLS033A",
                     "BLS044A",
                     "BLS054A",
                     "BLS058A",
                     "BLS002A",
                     "BLS003A",
                     "BLS008A",
                     "BLS011A",
                     "BLS012A",
                     "BLS014A",
                     "BLS025A",
                     "BLS026A",
                     "BLS027A",
                     "BLS028A",
                     "BLS029A",
                     "BLS030A",
                     "BLS032A",
                     "BLS034A",
                     "BLS035A",
                     "BLS036A",
                     "BLS037A",
                     "BLS038A",
                     "BLS039A",
                     "BLS040A",
                     "BLS041A",
                     "BLS043A",
                     "BLS045A",
                     "BLS048A",
                     "BLS049A",
                     "BLS050A",
                     "BLS051A",
                     "BLS052A",
                     "BLS053A",
                     "BLS055A",
                     "BLS056A",
                     "BLS059A",
                     "BLS060A",
                     "BLS062A",
                     "BLS064A",
                     "BLS065A",
                     "BLS066A",
                     "BLS070A",
                     "BLS073A",
                     "BLS074A",
                     "BLS075A",
                     "BLS078A",
                     "BLS079A",
                     "BLS081A",
                     "BLS083A",
                     "BLS084A",
                     "BLS086A")
# pull data
ds <- data.frame(desired_fields)
dat<- redcap_read(
  batch_size=300,
  records= participants.records.v1,
  redcap_uri = uri, 
  token      = beach_token, 
  fields     = desired_fields
)$data
head(dat)
```

```{r variable cleaning, include=FALSE}
dat.f=dat %>%
  select(-redcap_event_name,-redcap_repeat_instrument,-redcap_repeat_instance) %>%
  mutate(hispanic = recode(mom3t_hispanic, 
                                 "0"="Unchecked","1"="No, I am not Hispanic or Latino","2"="Yes, I am Hispanic or Latino"),
         American_Indian_or_Native_Alaskan_Mom    = recode(mom3t_race___1, 
                                  "0"="Unchecked","1"="Checked"),
         Asian_Mom  = recode(mom3t_race___2,
                               "0"="Unchecked","1"="Checked"),
         Black_or_African_American_Mom    = recode(mom3t_race___3, 
                                  "0"="Unchecked","1"="Checked"),
         Pacific_Islander_Mom = recode(mom3t_race___4, 
                               "0"="Unchecked","1"="Checked"),
         White_Mom    = recode(mom3t_race___5, 
                               "0"="Unchecked","1"="Checked"),
         mom3t_baby_sex    = recode(mom3t_baby_sex, 
                                    "1"="Male","2"="Female"),
         mom3t_baby_hispanic    = recode(mom3t_baby_hispanic, 
                                         "0"="Unchecked","1"="No, I am not Hispanic or Latino","2"="Yes, I am Hispanic or Latino"),
         American_Indian_or_Native_Alaskan_Baby    = recode(mom3t_baby_race___1,
                                       "0"="Unchecked","1"="Checked"),
         Asian_Baby    = recode(mom3t_baby_race___2, 
                                       "0"="Unchecked","1"="Checked"),
         Black_or_African_American_Baby    = recode(mom3t_baby_race___3, 
                                       "0"="Unchecked","1"="Checked"),
         Pacific_Islander_Baby    = recode(mom3t_baby_race___4, 
                                       "0"="Unchecked","1"="Checked"),
         White_Baby    = recode(mom3t_baby_race___5, 
"0"="Unchecked","1"="Checked"))%>%

  
  distinct()
```

```{r, echo=FALSE, include=FALSE, warning = FALSE}
 hispanic <- dat.f %>%
  filter(hispanic == "Yes, I am Hispanic or Latino")

hispanic <- hispanic%>%
  select(White_Mom,Black_or_African_American_Mom,
         Pacific_Islander_Mom,Asian_Mom,
         American_Indian_or_Native_Alaskan_Mom)%>%
  rename(White=White_Mom,Black_or_African_American=Black_or_African_American_Mom,Pacific_Islander=Pacific_Islander_Mom,Asian=Asian_Mom,American_Indian_or_Native_Alaskan=American_Indian_or_Native_Alaskan_Mom)
#%>%
 # group_by(White_Mom,Black_or_African_American_Mom,
  #         Pacific_Islander_Mom,Asian_Mom,
   #        American_Indian_or_Native_Alaskan_Mom)
hispanic
```

```{r, echo=FALSE, include=FALSE, warning = FALSE}
hispanic_baby <- dat.f %>%
  filter(mom3t_baby_sex=="Female")%>%
  filter(mom3t_baby_hispanic == "Yes, I am Hispanic or Latino")



hispanic_baby <- hispanic_baby%>%
  select(American_Indian_or_Native_Alaskan_Baby,Asian_Baby,
         Black_or_African_American_Baby,Pacific_Islander_Baby,
         White_Baby)%>%
  rename(White=White_Baby,Black_or_African_American=Black_or_African_American_Baby,Pacific_Islander=Pacific_Islander_Baby,Asian=Asian_Baby,American_Indian_or_Native_Alaskan=American_Indian_or_Native_Alaskan_Baby)
#%>%
#  group_by(American_Indian_or_Native_Alaskan_Baby,Asian_Baby,
#           Black_or_African_American_Baby,Pacific_Islander_Baby,
#           White_Baby)%>%
#  summarise(count=n())
hispanic_baby

```

```{r, echo=FALSE, include=FALSE, warning = FALSE}
hispanic_baby_m <- dat.f %>%
  filter(mom3t_baby_sex=="Male")%>%
  filter(mom3t_baby_hispanic == "Yes, I am Hispanic or Latino")

hispanic_baby_m <- hispanic_baby_m%>%
  select(American_Indian_or_Native_Alaskan_Baby,Asian_Baby,
         Black_or_African_American_Baby,Pacific_Islander_Baby,
         White_Baby)%>%
  rename(WhiteM=White_Baby,Black_or_African_AmericanM=Black_or_African_American_Baby,Pacific_IslanderM=Pacific_Islander_Baby,AsianM=Asian_Baby,American_Indian_or_Native_AlaskanM=American_Indian_or_Native_Alaskan_Baby)
  #group_by(American_Indian_or_Native_Alaskan_Baby,Asian_Baby,
  #         Black_or_African_American_Baby,Pacific_Islander_Baby,
  #         White_Baby)%>%
  #summarise(count=n())

hispanic_baby_m

temp <- nrow(hispanic_baby_m)
as.integer(temp)
hispanic_baby_m <- as.data.frame(t(as.matrix(hispanic_baby_m)))


xm <- data.frame("demographic"=c("White","Black_or_African_American","Pacific_Islander","Asian","American_Indian_or_Native_Alaskan","Other"), "Male"=c(0,0,0,0,0,0))

for (rows in hispanic_baby_m) {
  index <- 0
  temp <- 0
  temp_2 <- 0
  for (demo in rows) {

    index <- index+1
    if(demo == "Checked"){
      temp <- temp+1
      temp_2 <- index
      if(temp>1){
        xm[6, 2]<- xm[6, 2]+1
        break
      }
    }
  }
  if(temp<2)
  xm[temp_2, 2] <- xm[temp_2, 2]+1
}
```

```{r, Hispanic Female,echo=FALSE, include=FALSE, warning = FALSE}
hispanic_F <- bind_rows(hispanic,hispanic_baby)

temp <- nrow(hispanic_F)
as.integer(temp)
hispanic_F <- as.data.frame(t(as.matrix(hispanic_F)))



x <- data.frame("demographic"=c("White","Black_or_African_American","Pacific_Islander","Asian","American_Indian_or_Native_Alaskan","Other"), "Female"=c(0,0,0,0,0,0))

for (rows in hispanic_F) {
  index <- 0
  temp <- 0
  temp_2 <- 0
  for (demo in rows) {

    index <- index+1
    if(demo == "Checked"){
      temp <- temp+1
      temp_2 <- index
      if(temp>1){
        x[6, 2]<- x[6, 2]+1
        break
      }
    }
  }
  if(temp<2)
  x[temp_2, 2] <- x[temp_2, 2]+1
}

Hispanic <- full_join(x,xm)


```


```{r, warning=FALSE, echo=FALSE, include=FALSE, }
Not_hispanic <- dat.f %>%
  filter(mom3t_hispanic == 1)

Not_hispanic <- Not_hispanic%>%
  select(White_Mom,Black_or_African_American_Mom,
         Pacific_Islander_Mom,Asian_Mom,
         American_Indian_or_Native_Alaskan_Mom)%>%
  rename(White=White_Mom,Black_or_African_American=Black_or_African_American_Mom,Pacific_Islander=Pacific_Islander_Mom,Asian=Asian_Mom,American_Indian_or_Native_Alaskan=American_Indian_or_Native_Alaskan_Mom)
#%>%
#  group_by(White_Mom,Black_or_African_American_Mom,
#           Pacific_Islander_Mom,Asian_Mom,
#           American_Indian_or_Native_Alaskan_Mom)%>%
#  summarise(count=n())

Not_hispanic
```

```{r, warning=FALSE, echo=FALSE, include=FALSE, }
Not_hispanic_baby <- dat.f %>%
  filter(mom3t_baby_sex=="Female")%>%  
  filter(mom3t_baby_hispanic == "No, I am not Hispanic or Latino")

Not_hispanic_baby <- Not_hispanic_baby%>%
  select(American_Indian_or_Native_Alaskan_Baby,Asian_Baby,
         Black_or_African_American_Baby,Pacific_Islander_Baby,
         White_Baby)%>%
  rename(White=White_Baby,Black_or_African_American=Black_or_African_American_Baby,Pacific_Islander=Pacific_Islander_Baby,Asian=Asian_Baby,American_Indian_or_Native_Alaskan=American_Indian_or_Native_Alaskan_Baby)
#%>%
#  group_by(American_Indian_or_Native_Alaskan_Baby,Asian_Baby,
#           Black_or_African_American_Baby,Pacific_Islander_Baby,
#           White_Baby)%>%
#  summarise(count=n())

Not_hispanic_baby
```

```{r, warning=FALSE, echo=FALSE, include=FALSE, }
Not_hispanic_baby_m <- dat.f %>%
  filter(mom3t_baby_sex=="Male")%>%  
  filter(mom3t_baby_hispanic == "No, I am not Hispanic or Latino")

Not_hispanic_baby_m <- Not_hispanic_baby_m%>%
  select(American_Indian_or_Native_Alaskan_Baby,Asian_Baby,
         Black_or_African_American_Baby,Pacific_Islander_Baby,
         White_Baby)%>%
  rename(WhiteM=White_Baby,Black_or_African_AmericanM=Black_or_African_American_Baby,Pacific_IslanderM=Pacific_Islander_Baby,AsianM=Asian_Baby,American_Indian_or_Native_AlaskanM=American_Indian_or_Native_Alaskan_Baby)
#  group_by(American_Indian_or_Native_Alaskan_Baby,Asian_Baby,
#           Black_or_African_American_Baby,Pacific_Islander_Baby,
#           White_Baby)%>%
#  summarise(count=n())



temp <- nrow(Not_hispanic_baby_m)
as.integer(temp)
Not_hispanic_baby_m <- as.data.frame(t(as.matrix(Not_hispanic_baby_m)))

nm <- data.frame("demographic"=c("White","Black_or_African_American","Pacific_Islander","Asian","American_Indian_or_Native_Alaskan","Other"), "MaleN"=c(0,0,0,0,0,0))

for (rows in Not_hispanic_baby_m) {
  index <- 0
  temp <- 0
  temp_2 <- 0
  for (demo in rows) {

    index <- index+1
    if(demo == "Checked"){
      temp <- temp+1
      temp_2 <- index
      if(temp>1){
        nm[6, 2]<- nm[6, 2]+1
        break
      }
    }
  }
  if(temp<2)
  nm[temp_2, 2] <- nm[temp_2, 2]+1
}

```

```{r, Non-Hispanic Female, warning=FALSE, echo=FALSE}
non_hispanic_F <- bind_rows(Not_hispanic,Not_hispanic_baby)

temp <- nrow(non_hispanic_F)
as.integer(temp)
non_hispanic_F <- as.data.frame(t(as.matrix(non_hispanic_F)))


n <- data.frame("demographic"=c("White","Black_or_African_American","Pacific_Islander","Asian","American_Indian_or_Native_Alaskan","Other"), "FemaleN"=c(0,0,0,0,0,0))

for (rows in non_hispanic_F) {
  index <- 0
  temp <- 0
  temp_2 <- 0
  for (demo in rows) {

    index <- index+1
    if(demo == "Checked"){
      temp <- temp+1
      temp_2 <- index
      if(temp>1){
        n[6, 2]<- n[6, 2]+1
        break
      }
    }
  }
  if(temp<2)
  n[temp_2, 2] <- n[temp_2, 2]+1
}

Not_Hispanic <- full_join(n,nm)
```


## Final Table of demographic breakdown following formatting by the NIH
```{r, Overview Table, warning=FALSE,echo=FALSE}

finaleTable <- full_join(Hispanic,Not_Hispanic)%>%
  mutate(Total=Female+Male+FemaleN+MaleN)



  gt(data = finaleTable)%>%
  tab_header(
    title = "Demographic breakdown",
    subtitle = "Lemas Lab BEACH study"
  )%>%
  tab_spanner(
    label = "Hispanic",
    columns = vars(Female, Male)
  )%>%
    tab_spanner(
      label = "Not Hispanic",
      columns = vars(FemaleN,MaleN)
    )%>%
  summary_rows(
      columns = vars(Female,Male,FemaleN,MaleN,Total),
      fns=list(total="sum")
    )%>%
  tab_options(
      summary_row.background.color = "lightblue"
    )
    

```




